// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/arithmetic.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArithmeticRequest struct {
	RequestType          string   `protobuf:"bytes,1,opt,name=requestType,proto3" json:"requestType,omitempty"`
	A                    int32    `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArithmeticRequest) Reset()         { *m = ArithmeticRequest{} }
func (m *ArithmeticRequest) String() string { return proto.CompactTextString(m) }
func (*ArithmeticRequest) ProtoMessage()    {}
func (*ArithmeticRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d845eebf15ff7937, []int{0}
}

func (m *ArithmeticRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArithmeticRequest.Unmarshal(m, b)
}
func (m *ArithmeticRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArithmeticRequest.Marshal(b, m, deterministic)
}
func (m *ArithmeticRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArithmeticRequest.Merge(m, src)
}
func (m *ArithmeticRequest) XXX_Size() int {
	return xxx_messageInfo_ArithmeticRequest.Size(m)
}
func (m *ArithmeticRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArithmeticRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArithmeticRequest proto.InternalMessageInfo

func (m *ArithmeticRequest) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *ArithmeticRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *ArithmeticRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type ArithmeticResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArithmeticResponse) Reset()         { *m = ArithmeticResponse{} }
func (m *ArithmeticResponse) String() string { return proto.CompactTextString(m) }
func (*ArithmeticResponse) ProtoMessage()    {}
func (*ArithmeticResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d845eebf15ff7937, []int{1}
}

func (m *ArithmeticResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArithmeticResponse.Unmarshal(m, b)
}
func (m *ArithmeticResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArithmeticResponse.Marshal(b, m, deterministic)
}
func (m *ArithmeticResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArithmeticResponse.Merge(m, src)
}
func (m *ArithmeticResponse) XXX_Size() int {
	return xxx_messageInfo_ArithmeticResponse.Size(m)
}
func (m *ArithmeticResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArithmeticResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArithmeticResponse proto.InternalMessageInfo

func (m *ArithmeticResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ArithmeticResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*ArithmeticRequest)(nil), "pb.ArithmeticRequest")
	proto.RegisterType((*ArithmeticResponse)(nil), "pb.ArithmeticResponse")
}

func init() { proto.RegisterFile("pb/arithmetic.proto", fileDescriptor_d845eebf15ff7937) }

var fileDescriptor_d845eebf15ff7937 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0xd2, 0x4f,
	0x2c, 0xca, 0x2c, 0xc9, 0xc8, 0x4d, 0x2d, 0xc9, 0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe4, 0x12, 0x74, 0x84, 0x8b, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x29, 0x70, 0x71, 0x17, 0x41, 0x98, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0xc8, 0x42, 0x42, 0x3c, 0x5c, 0x8c, 0x89, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x8c, 0x89, 0x20, 0x5e, 0x92, 0x04, 0x33, 0x84, 0x97, 0xa4, 0x64, 0xc7, 0x25, 0x84, 0x6c,
	0x64, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e,
	0x09, 0xd8, 0x38, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x80, 0x8b, 0x39, 0xb5, 0xa8, 0x08, 0x6c, 0x16,
	0x67, 0x10, 0x88, 0x69, 0x84, 0xe2, 0xa4, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x1b,
	0x2e, 0x4e, 0xe7, 0xc4, 0x9c, 0xe4, 0xd2, 0x9c, 0xc4, 0x92, 0x54, 0x21, 0x51, 0xbd, 0x82, 0x24,
	0x3d, 0x0c, 0x67, 0x4b, 0x89, 0xa1, 0x0b, 0x43, 0xac, 0x56, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xd8,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x90, 0xde, 0xbe, 0xef, 0x07, 0x01, 0x00, 0x00,
}
